# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3
pipelines:
   branches:
      master:
           - step:
               deployment: production
               caches:
               - node
               script:
               - npm install -g firebase-tools
               - firebase deploy --token=1//03EWBYAKG708CCgYIARAAGAMSNwF-L9IrdvgxNNpL-1Zh51S8n9C-e0JBjRP1SIq2OJtio1VLIKEAqOTJGWlO1C5Oft3dq-tGupE --project jskit-app  --non-interactive